// BT-19 momentum badge: how the Resilience Index has moved since the last
// publication, with a lightweight sparkline of the comparable window.
//
// The component is deliberately dumb — `computeMomentum` (src/utils/momentum.js)
// owns every judgement about what may be compared. Three states exist and each
// has honest copy, because the common case on a daily rebuild of annual data is
// no movement at all:
//   changed  -> a signed delta against the previous published point
//   flat     -> "No change since <the day it last moved>"
//   unknown  -> the first reading after a methodology break; no delta exists
// A missing history artifact renders nothing rather than an error: the file is
// auxiliary (Option A) and is generated by the refresh workflow, not committed.

import { useTranslation } from 'react-i18next';
import { sparklineGeometry } from '../utils/momentum';
import { formatShortDate } from '../utils/formatDate';

const SPARKLINE = { width: 72, height: 20, padding: 2 };

const DIRECTION_TONE = {
  up: 'var(--color-green)',
  down: 'var(--color-red)',
  flat: 'var(--color-muted)',
  unknown: 'var(--color-muted)',
};

const DIRECTION_GLYPH = { up: '▲', down: '▼' };

function formatDelta(delta) {
  const rounded = Math.round(Math.abs(delta) * 10) / 10;
  return `${delta > 0 ? '+' : '−'}${rounded.toFixed(1)}`;
}

function Sparkline({ geometry, tone, label }) {
  if (!geometry) return null;

  return (
    <svg
      role="img"
      aria-label={label}
      width={SPARKLINE.width}
      height={SPARKLINE.height}
      viewBox={`0 0 ${SPARKLINE.width} ${SPARKLINE.height}`}
      style={{ display: 'block', overflow: 'visible', flexShrink: 0 }}
    >
      <path
        d={geometry.path}
        fill="none"
        stroke={tone}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        // A single-point window has no line to draw; the end marker below still
        // shows where the series currently sits.
        strokeDasharray={geometry.coordinates.length > 1 ? undefined : '0 1'}
      />
      <circle cx={geometry.last.x} cy={geometry.last.y} r="2" fill={tone} />
    </svg>
  );
}

/**
 * Direction counts for the all-Borneo scope.
 *
 * The client asked to see direction beside the score, and all-Borneo is the
 * default view. But the aggregate index is the mean of cross-territory pillar
 * averages, not the mean of the four territory indices, so no aggregate delta
 * can be recovered from a per-territory history. Counting how many territories
 * rose and fell answers "which way is Borneo moving?" from data we actually
 * hold, instead of publishing a Borneo-wide number we cannot derive.
 */
export function MomentumSummary({ summary, style }) {
  const { t } = useTranslation();

  if (!summary?.total) return null;

  return (
    <div style={{ fontSize: 11, color: 'var(--color-muted)', lineHeight: 1.45, ...style }}>
      {t('momentum.summary', summary)}
      {summary.unknown > 0 ? ` ${t('momentum.summaryUnknown', summary)}` : null}
    </div>
  );
}

/**
 * BT-19's "biggest movers" for a scope that has no series of its own.
 *
 * All-Borneo is an average of whichever territories are scored that day, so
 * there is no aggregate history to plot; naming the territories that actually
 * moved is the honest equivalent. A quiet day lists nothing rather than four
 * zeroes.
 */
export function MomentumMovers({ movers, style }) {
  const { t } = useTranslation();

  if (!Array.isArray(movers)) return null;

  if (!movers.length) {
    return (
      <div style={{ fontSize: 11, color: 'var(--color-muted)', ...style }}>{t('momentum.moversNone')}</div>
    );
  }

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap', fontSize: 11, ...style }}>
      <span style={{ color: 'var(--color-muted)' }}>{t('momentum.moversLabel')}</span>
      {movers.map((mover) => (
        <span key={mover.territory} style={{ color: DIRECTION_TONE[mover.direction], fontWeight: 600 }}>
          {t('momentum.moverItem', { territory: mover.territory, delta: formatDelta(mover.delta) })}
        </span>
      ))}
    </div>
  );
}

export default function MomentumBadge({ momentum, style }) {
  const { t, i18n } = useTranslation();

  if (!momentum?.current) return null;

  const { direction, delta, points, current, previous, lastChangeDate, comparableSince, hasMethodologyBreak } =
    momentum;
  const tone = DIRECTION_TONE[direction] || DIRECTION_TONE.unknown;
  const geometry = sparklineGeometry(points, SPARKLINE);
  const format = (value) => formatShortDate(value, i18n.language);

  let text;
  if (direction === 'up' || direction === 'down') {
    text = t('momentum.changed', { delta: formatDelta(delta), date: format(previous.date) });
  } else if (direction === 'flat') {
    // Falls back to the window start when the value has not moved once since
    // the current method began — there is no "last changed" day to name.
    text = t('momentum.flat', { date: format(lastChangeDate || comparableSince) });
  } else {
    text = t('momentum.firstReading', { date: format(comparableSince || current.date) });
  }

  const methodologyNote = hasMethodologyBreak ? t('momentum.methodologyNote') : null;

  return (
    <div
      style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', minWidth: 0, ...style }}
    >
      <Sparkline
        geometry={geometry}
        tone={tone}
        label={t('momentum.sparklineLabel', {
          start: format(points[0]?.date),
          end: format(current.date),
        })}
      />
      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 11, color: tone }}>
        {DIRECTION_GLYPH[direction] ? (
          <span aria-label={t(`momentum.direction_${direction}`)} role="img" style={{ fontSize: 9 }}>
            {DIRECTION_GLYPH[direction]}
          </span>
        ) : null}
        <span style={{ fontWeight: direction === 'up' || direction === 'down' ? 700 : 500 }}>{text}</span>
      </span>
      {methodologyNote ? (
        <span
          title={methodologyNote}
          style={{ fontSize: 10, color: 'var(--color-muted)', maxWidth: '100%' }}
        >
          {methodologyNote}
        </span>
      ) : null}
    </div>
  );
}
